DROP DATABASE IF EXISTS `gmairData`;
CREATE DATABASE `gmairData` DEFAULT CHARACTER SET UTF8MB4;
USE `gmairData`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `userId` BIGINT,
  `userName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`userId`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;

DROP TABLE IF EXISTS `machineStatus`;
CREATE TABLE `machineStatus` (
    `uid` VARCHAR(64) NOT NULL,
    PRIMARY KEY (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;