DROP DATABASE IF EXISTS `gmairData`;
CREATE DATABASE `gmairData` DEFAULT CHARACTER SET UTF8MB4;
USE `gmairData`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `userId` BIGINT,
  `userName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
